const express = require('express');
const session = require('express-session');
const bodyParser = require('body-parser');
const path = require('path');
const db = require('../database/init');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, '../public')));
app.use(express.static(path.join(__dirname, '../admin')));

// Session configuration
app.use(session({
  secret: 'jersivo-secret-key-2024-secure',
    resave: false,
      saveUninitialized: false,
        cookie: { 
            secure: false,
                maxAge: 24 * 60 * 60 * 1000
                  }
                  }));

                  // Admin credentials
                  const ADMIN_USERNAME = 'sam@jersivo007';
                  const ADMIN_PASSWORD = 'stg@jer@2009*#';

                  // Authentication middleware
                  const isAuthenticated = (req, res, next) => {
                    if (req.session.isAdmin) {
                        next();
                          } else {
                              res.status(401).json({ error: 'Unauthorized' });
                                }
                                };

                                // Get all products
                                app.get('/api/products', (req, res) => {
                                  const { category, search, sort } = req.query;
                                    
                                      let query = 'SELECT * FROM products WHERE 1=1';
                                        const params = [];
                                          
                                            if (category && category !== 'all') {
                                                query += ' AND category = ?';
                                                    params.push(category);
                                                      }
                                                        
                                                          if (search) {
                                                              query += ' AND (name LIKE ? OR description LIKE ?)';
                                                                  params.push(`%${search}%`, `%${search}%`);
                                                                    }
                                                                      
                                                                        if (sort === 'price-asc') {
                                                                            query += ' ORDER BY price ASC';
                                                                              } else if (sort === 'price-desc') {
                                                                                  query += ' ORDER BY price DESC';
                                                                                    } else {
                                                                                        query += ' ORDER BY created_at DESC';
                                                                                          }
                                                                                            
                                                                                              db.all(query, params, (err, rows) => {
                                                                                                  if (err) {
                                                                                                        res.status(500).json({ error: err.message });
                                                                                                            } else {
                                                                                                                  res.json(rows);
                                                                                                                      }
                                                                                                                        });
                                                                                                                        });

                                                                                                                        // Get featured products
                                                                                                                        app.get('/api/products/featured', (req, res) => {
                                                                                                                          db.all('SELECT * FROM products WHERE featured = 1 ORDER BY created_at DESC LIMIT 6', (err, rows) => {
                                                                                                                              if (err) {
                                                                                                                                    res.status(500).json({ error: err.message });
                                                                                                                                        } else {
                                                                                                                                              res.json(rows);
                                                                                                                                                  }
                                                                                                                                                    });
                                                                                                                                                    });

                                                                                                                                                    // Get single product
                                                                                                                                                    app.get('/api/products/:id', (req, res) => {
                                                                                                                                                      db.get('SELECT * FROM products WHERE id = ?', [req.params.id], (err, row) => {
                                                                                                                                                          if (err) {
                                                                                                                                                                res.status(500).json({ error: err.message });
                                                                                                                                                                    } else if (!row) {
                                                                                                                                                                          res.status(404).json({ error: 'Product not found' });
                                                                                                                                                                              } else {
                                                                                                                                                                                    res.json(row);
                                                                                                                                                                                        }
                                                                                                                                                                                          });
                                                                                                                                                                                          });

                                                                                                                                                                                          // Get categories
                                                                                                                                                                                          app.get('/api/categories', (req, res) => {
                                                                                                                                                                                            db.all('SELECT DISTINCT category FROM products', (err, rows) => {
                                                                                                                                                                                                if (err) {
                                                                                                                                                                                                      res.status(500).json({ error: err.message });
                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                res.json(rows.map(row => row.category));
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                      });

                                                                                                                                                                                                                      // Admin login
                                                                                                                                                                                                                      app.post('/api/admin/login', (req, res) => {
                                                                                                                                                                                                                        const { username, password } = req.body;
                                                                                                                                                                                                                          
                                                                                                                                                                                                                            if (username === ADMIN_USERNAME && password === ADMIN_PASSWORD) {
                                                                                                                                                                                                                                req.session.isAdmin = true;
                                                                                                                                                                                                                                    res.json({ success: true, message: 'Login successful' });
                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                          res.status(401).json({ error: 'Invalid credentials' });
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                            // Admin logout
                                                                                                                                                                                                                                            app.post('/api/admin/logout', (req, res) => {
                                                                                                                                                                                                                                              req.session.destroy();
                                                                                                                                                                                                                                                res.json({ success: true });
                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                // Check admin status
                                                                                                                                                                                                                                                app.get('/api/admin/status', (req, res) => {
                                                                                                                                                                                                                                                  res.json({ isAdmin: !!req.session.isAdmin });
                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                  // Add product
                                                                                                                                                                                                                                                  app.post('/api/admin/products', isAuthenticated, (req, res) => {
                                                                                                                                                                                                                                                    const { name, price, category, image1, image2, description, featured } = req.body;
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        const query = `
                                                                                                                                                                                                                                                            INSERT INTO products (name, price, category, image1, image2, description, featured)
                                                                                                                                                                                                                                                                VALUES (?, ?, ?, ?, ?, ?, ?)
                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                      db.run(query, [name, price, category, image1, image2 || null, description, featured ? 1 : 0], function(err) {
                                                                                                                                                                                                                                                                          if (err) {
                                                                                                                                                                                                                                                                                res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                          res.json({ 
                                                                                                                                                                                                                                                                                                  success: true, 
                                                                                                                                                                                                                                                                                                          id: this.lastID,
                                                                                                                                                                                                                                                                                                                  message: 'Product added successfully'
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                              // Update product
                                                                                                                                                                                                                                                                                                                              app.put('/api/admin/products/:id', isAuthenticated, (req, res) => {
                                                                                                                                                                                                                                                                                                                                const { name, price, category, image1, image2, description, featured } = req.body;
                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                    const query = `
                                                                                                                                                                                                                                                                                                                                        UPDATE products 
                                                                                                                                                                                                                                                                                                                                            SET name = ?, price = ?, category = ?, image1 = ?, image2 = ?, description = ?, featured = ?
                                                                                                                                                                                                                                                                                                                                                WHERE id = ?
                                                                                                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                      db.run(query, [name, price, category, image1, image2 || null, description, featured ? 1 : 0, req.params.id], function(err) {
                                                                                                                                                                                                                                                                                                                                                          if (err) {
                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                    } else if (this.changes === 0) {
                                                                                                                                                                                                                                                                                                                                                                          res.status(404).json({ error: 'Product not found' });
                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                    res.json({ success: true, message: 'Product updated successfully' });
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                          // Delete product
                                                                                                                                                                                                                                                                                                                                                                                          app.delete('/api/admin/products/:id', isAuthenticated, (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                            db.run('DELETE FROM products WHERE id = ?', [req.params.id], function(err) {
                                                                                                                                                                                                                                                                                                                                                                                                if (err) {
                                                                                                                                                                                                                                                                                                                                                                                                      res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                                                          } else if (this.changes === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                res.status(404).json({ error: 'Product not found' });
                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                          res.json({ success: true, message: 'Product deleted successfully' });
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                // Serve public homepage
                                                                                                                                                                                                                                                                                                                                                                                                                                app.get('/', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                  res.sendFile(path.join(__dirname, '../public/index.html'));
                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                  // Serve admin panel
                                                                                                                                                                                                                                                                                                                                                                                                                                  app.get('/admin', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                    res.sendFile(path.join(__dirname, '../admin/admin.html'));
                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                    // Start server
                                                                                                                                                                                                                                                                                                                                                                                                                                    app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`
                                                                                                                                                                                                                                                                                                                                                                                                                                        ╔═══════════════════════════════════════╗
                                                                                                                                                                                                                                                                                                                                                                                                                                          ║     JERSIVO STORE SERVER RUNNING      ║
                                                                                                                                                                                                                                                                                                                                                                                                                                            ╠═══════════════════════════════════════╣
                                                                                                                                                                                                                                                                                                                                                                                                                                              ║  Port: ${PORT}                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                ║  URL:  http://localhost:${PORT}         
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ║  Admin: http://localhost:${PORT}/admin  
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ╚═══════════════════════════════════════╝
                                                                                                                                                                                                                                                                                                                                                                                                                                                      `);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      });