const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const googleSheets = require('../server/googleSheets');

// SQLite database (temporary cache only)
const dbPath = path.join(__dirname, 'jersivo.db');
const db = new sqlite3.Database(dbPath);

// Initialize SQLite tables (for temporary caching)
db.serialize(() => {
  // Products table (temporary cache)
    db.run(`
        CREATE TABLE IF NOT EXISTS products (
              id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                          price INTEGER NOT NULL,
                                category TEXT NOT NULL,
                                      image1 TEXT NOT NULL,
                                            image2 TEXT,
                                                  description TEXT,
                                                        customisable TEXT,
                                                              sizes TEXT,
                                                                    label TEXT NOT NULL,
                                                                          status TEXT DEFAULT 'LIVE',
                                                                                created_at TEXT,
                                                                                      created_by TEXT,
                                                                                            last_modified_at TEXT,
                                                                                                  last_modified_by TEXT
                                                                                                      )
                                                                                                        `);

                                                                                                          console.log('✅ SQLite cache database initialized');
                                                                                                          });

                                                                                                          /**
                                                                                                           * Sync products from Google Sheets to SQLite cache
                                                                                                            * @param {string} sheetName - Name of the sheet to sync
                                                                                                             */
                                                                                                             async function syncProductsToCache() {
  try {
    console.log('📊 Syncing products from Google Sheets to cache...');
    
    const products = await googleSheets.readProducts('Sheet1');
    
    // Filter only LIVE products (exclude DELETION_PENDING)
    const liveProducts = products.filter(p => p.status !== 'DELETION_PENDING');
    
    // Clear existing cache
    db.run('DELETE FROM products', (err) => {
      if (err) {
        console.error('Error clearing cache:', err);
      }
    });
    
    // Use INSERT OR REPLACE to handle duplicates
    const stmt = db.prepare(`
      INSERT OR REPLACE INTO products (id, name, price, category, image1, image2, description, customisable, sizes, label)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);
    
    for (const product of liveProducts) {
      stmt.run(
        product.id,
        product.name,
        product.price,
        product.category,
        product.image1,
        product.image2 || '',
        product.description || '',
        product.customisable || 'No',
        product.sizes || '0',
        product.label || 'NEW'
      );
    }
    
    stmt.finalize();
    
    console.log(`✅ Synced ${liveProducts.length} products to cache`);
  } catch (error) {
    console.error('Error syncing products to cache:', error);
    throw error; // Don't crash the server
  }
}
                                                                                                                                                                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                                                                                                                                                                            * Get all products from cache
                                                                                                                                                                                                                                                                                                                                                                                                                             * @param {Object} filters - Optional filters (category, search, etc.)
                                                                                                                                                                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                                                                                                                                                                              function getProductsFromCache(filters = {}) {
                                                                                                                                                                                                                                                                                                                                                                                                                                return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                    let query = 'SELECT * FROM products WHERE status = "LIVE"';
                                                                                                                                                                                                                                                                                                                                                                                                                                        const params = [];

                                                                                                                                                                                                                                                                                                                                                                                                                                            if (filters.category && filters.category !== 'all') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  query += ' AND category = ?';
                                                                                                                                                                                                                                                                                                                                                                                                                                                        params.push(filters.category);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (filters.search) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      query += ' AND (name LIKE ? OR description LIKE ? OR category LIKE ? OR id LIKE ?)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const searchTerm = `%${filters.search}%`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  params.push(searchTerm, searchTerm, searchTerm, searchTerm);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (filters.sort) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (filters.sort === 'price_asc') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        query += ' ORDER BY price ASC';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else if (filters.sort === 'price_desc') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      query += ' ORDER BY price DESC';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (filters.sort === 'name') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    query += ' ORDER BY name ASC';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  db.all(query, params, (err, rows) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reject(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              resolve(rows);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * Clear cache (useful for refreshing data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function clearCache() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  db.run('DELETE FROM products', (err) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (err) reject(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              else resolve(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Export database and helper functions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    module.exports = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      db,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        syncProductsToCache,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          getProductsFromCache,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            clearCache,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              googleSheets, // Export googleSheets for direct access if needed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
